apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-deploy
  name: python-deploy
spec:
  ports:
  - name: 80-8000
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: python-deploy
  type: NodePort
status:
  loadBalancer: {}
